import type { Metadata } from "next";
import "./globals.css";
import SolanaProvider from "./context/providers";
import { Toaster } from 'sonner'

// Using system fonts to avoid network font downloads in dev/build

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`antialiased p-0 m-0 bg-slate-900 text-slate-100`}
      >
        <SolanaProvider>
          {children}
          <Toaster richColors position="top-right" />
        </SolanaProvider>
      </body>
    </html>
  );
}
